#!/usr/bin/env bash
#
# Install symlinks to files. Script from Dave Eddy
#
# install all files to ~ by symlinking them,
# this way, updating them is as simple as git pull
#
# Install some LSP engines for Code completion support
#
# Original Author: Dave Eddy <dave@daveeddy.com>

# verbose ln, because `ln -v` is not portable
symlink() {
	printf '%55s -> %s\n' "${1/#$HOME/\~}" "${2/#$HOME/\~}"
	ln -nsf "$@"
}

# Link dotfiles
dotfiles=(
    bashrc
    gitconfig
	vimrc
	vim
)
for f in "${dotfiles[@]}"; do
	[[ -d ~/.$f && ! -L ~/.$f ]] && rm -r ~/."$f"
	symlink "$PWD/$f" ~/."$f"
done


if [[ ! -z $1 && $1 == '--YCMpackages' ]]; then
    echo 'Installing packages for YouCompleteMe'
    sudo apt install build-essential cmake vim-nox python3-dev mono-complete golang nodejs openjdk-17-jdk openjdk-17-jre npm
fi

if [[ -t 1 ]]; then
	vim '+PlugInstall --sync' +qa
else
	printf "may need to run:\n\tvim +'PlugInstall --sync' +qa\n"
fi

true

