#!/usr/bin/env bash
#
# Install symlinks to files. Script from Dave Eddy
#
# install all files to ~ by symlinking them,
# this way, updating them is as simple as git pull
#
# Original Author: Dave Eddy <dave@daveeddy.com>

# verbose ln, because `ln -v` is not portable
symlink() {
	printf '%55s -> %s\n' "${1/#$HOME/\~}" "${2/#$HOME/\~}"
	ln -nsf "$@"
}

# Link dotfiles
dotfiles=(
    bashrc
    gitconfig
	vimrc
)
for f in "${dotfiles[@]}"; do
	[[ -d ~/.$f && ! -L ~/.$f ]] && rm -r ~/."$f"
	symlink "$PWD/$f" ~/."$f"
done

# Create some files for use later
touch ~/.local.vimrc
mkdir ~/.vim

# Check for curl
if ! command -v curl &> /dev/null; then
    echo "Error: curl is not installed. Cannot download vim-plug" >&2
    exit 1
fi

# Download and install the latest vim-plug
curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

# If we're interactive, then run the PlugInstall
if [[ -t 1 ]]; then
	vim '+PlugInstall --sync' +qa
else
	printf "May need to run:\n\tvim +'PlugInstall --sync' +qa\n"
fi

true

